#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.ocwebservice.locator.data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="owc_owens")]
	public partial class ContractorLocatorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRawBMContractorType(com.ocwebservice.locator.model.RawBMContractorType instance);
    partial void UpdateRawBMContractorType(com.ocwebservice.locator.model.RawBMContractorType instance);
    partial void DeleteRawBMContractorType(com.ocwebservice.locator.model.RawBMContractorType instance);
    partial void InsertRawBMContractor(com.ocwebservice.locator.model.RawBMContractor instance);
    partial void UpdateRawBMContractor(com.ocwebservice.locator.model.RawBMContractor instance);
    partial void DeleteRawBMContractor(com.ocwebservice.locator.model.RawBMContractor instance);
    partial void InsertRawBMContractorInfo(com.ocwebservice.locator.model.RawBMContractorInfo instance);
    partial void UpdateRawBMContractorInfo(com.ocwebservice.locator.model.RawBMContractorInfo instance);
    partial void DeleteRawBMContractorInfo(com.ocwebservice.locator.model.RawBMContractorInfo instance);
    partial void InsertRawBMLocation(com.ocwebservice.locator.model.RawBMLocation instance);
    partial void UpdateRawBMLocation(com.ocwebservice.locator.model.RawBMLocation instance);
    partial void DeleteRawBMLocation(com.ocwebservice.locator.model.RawBMLocation instance);
    #endregion
		
		public ContractorLocatorDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OwensCorning.Locator.Owens"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ContractorLocatorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContractorLocatorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContractorLocatorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContractorLocatorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<com.ocwebservice.locator.model.RawBMContractorType> RawBMContractorTypes
		{
			get
			{
				return this.GetTable<com.ocwebservice.locator.model.RawBMContractorType>();
			}
		}
		
		public System.Data.Linq.Table<com.ocwebservice.locator.model.RawBMContractor> RawBMContractors
		{
			get
			{
				return this.GetTable<com.ocwebservice.locator.model.RawBMContractor>();
			}
		}
		
		public System.Data.Linq.Table<com.ocwebservice.locator.model.RawBMContractorInfo> RawBMContractorInfos
		{
			get
			{
				return this.GetTable<com.ocwebservice.locator.model.RawBMContractorInfo>();
			}
		}
		
		public System.Data.Linq.Table<com.ocwebservice.locator.model.RawBMLocation> RawBMLocations
		{
			get
			{
				return this.GetTable<com.ocwebservice.locator.model.RawBMLocation>();
			}
		}
	}
}
namespace com.ocwebservice.locator.model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dealer_type_map")]
	public partial class RawBMContractorType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _dealer_id;
		
		private int _type_id;
		
		private char _DealerType;
		
		private EntityRef<RawBMContractor> _RawBMContractor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ondealer_idChanging(int value);
    partial void Ondealer_idChanged();
    partial void Ontype_idChanging(int value);
    partial void Ontype_idChanged();
    partial void OnDealerTypeChanging(char value);
    partial void OnDealerTypeChanged();
    #endregion
		
		public RawBMContractorType()
		{
			this._RawBMContractor = default(EntityRef<RawBMContractor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dealer_id", DbType="Int NOT NULL")]
		public int dealer_id
		{
			get
			{
				return this._dealer_id;
			}
			set
			{
				if ((this._dealer_id != value))
				{
					if (this._RawBMContractor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondealer_idChanging(value);
					this.SendPropertyChanging();
					this._dealer_id = value;
					this.SendPropertyChanged("dealer_id");
					this.Ondealer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_id", DbType="Int NOT NULL")]
		public int type_id
		{
			get
			{
				return this._type_id;
			}
			set
			{
				if ((this._type_id != value))
				{
					this.Ontype_idChanging(value);
					this.SendPropertyChanging();
					this._type_id = value;
					this.SendPropertyChanged("type_id");
					this.Ontype_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerType", DbType="VarChar(1) NOT NULL")]
		public char DealerType
		{
			get
			{
				return this._DealerType;
			}
			set
			{
				if ((this._DealerType != value))
				{
					this.OnDealerTypeChanging(value);
					this.SendPropertyChanging();
					this._DealerType = value;
					this.SendPropertyChanged("DealerType");
					this.OnDealerTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RawBMContractor_RawBMContractorType", Storage="_RawBMContractor", ThisKey="dealer_id", OtherKey="id", IsForeignKey=true)]
		public RawBMContractor RawBMContractor
		{
			get
			{
				return this._RawBMContractor.Entity;
			}
			set
			{
				RawBMContractor previousValue = this._RawBMContractor.Entity;
				if (((previousValue != value) 
							|| (this._RawBMContractor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RawBMContractor.Entity = null;
						previousValue.RawBMContractorTypes.Remove(this);
					}
					this._RawBMContractor.Entity = value;
					if ((value != null))
					{
						value.RawBMContractorTypes.Add(this);
						this._dealer_id = value.id;
					}
					else
					{
						this._dealer_id = default(int);
					}
					this.SendPropertyChanged("RawBMContractor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dealers")]
	public partial class RawBMContractor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _zip;
		
		private string _address1;
		
		private string _address2;
		
		private string _city;
		
		private string _state;
		
		private string _phone;
		
		private string _phone2;
		
		private string _store;
		
		private System.Nullable<int> _pp_id;
		
		private string _region;
		
		private System.Nullable<int> _tradearea;
		
		private string _salesrep;
		
		private string _contact;
		
		private bool _ProConnectFlag;
		
		private bool _showroom;
		
		private string _ctitle;
		
		private string _url;
		
		private System.Nullable<char> _DealerType;
		
		private System.DateTime _CreatedDate;
		
		private System.Nullable<System.DateTime> _UpdatedDate;
		
		private char _WebVisible;
		
		private char _IsPreferredPlat;
		
		private char _IsExFxCertified;
		
		private char _IsPreferredPride;
		
		private string _SalesRepFirstName;
		
		private string _SalesRepID;
		
		private string _SalesRepEmailID;
		
		private string _SalesRepUserName;
		
		private string _RegionName;
		
		private string _MemberEmailID;
		
		private char _IsQuietZoneBuilder;
		
		private char _Platinum_Pride_Award;
		
		private char _Top_Of_The_House_Certified;
		
		private char _Green_Pledge;
		
		private System.Nullable<int> _RewardsLevel;
		
		private char _Total_Protection_Rfg_System;
		
		private EntitySet<RawBMContractorType> _RawBMContractorTypes;
		
		private EntityRef<RawBMContractorInfo> _RawBMContractorInfo;
		
		private EntityRef<RawBMLocation> _RawBMLocation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnzipChanging(string value);
    partial void OnzipChanged();
    partial void Onaddress1Changing(string value);
    partial void Onaddress1Changed();
    partial void Onaddress2Changing(string value);
    partial void Onaddress2Changed();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void Onphone2Changing(string value);
    partial void Onphone2Changed();
    partial void OnstoreChanging(string value);
    partial void OnstoreChanged();
    partial void Onpp_idChanging(System.Nullable<int> value);
    partial void Onpp_idChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OntradeareaChanging(System.Nullable<int> value);
    partial void OntradeareaChanged();
    partial void OnsalesrepChanging(string value);
    partial void OnsalesrepChanged();
    partial void OncontactChanging(string value);
    partial void OncontactChanged();
    partial void OnProConnectFlagChanging(bool value);
    partial void OnProConnectFlagChanged();
    partial void OnshowroomChanging(bool value);
    partial void OnshowroomChanged();
    partial void OnctitleChanging(string value);
    partial void OnctitleChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnDealerTypeChanging(System.Nullable<char> value);
    partial void OnDealerTypeChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnUpdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedDateChanged();
    partial void OnWebVisibleChanging(char value);
    partial void OnWebVisibleChanged();
    partial void OnIsPreferredPlatChanging(char value);
    partial void OnIsPreferredPlatChanged();
    partial void OnIsExFxCertifiedChanging(char value);
    partial void OnIsExFxCertifiedChanged();
    partial void OnIsPreferredPrideChanging(char value);
    partial void OnIsPreferredPrideChanged();
    partial void OnSalesRepFirstNameChanging(string value);
    partial void OnSalesRepFirstNameChanged();
    partial void OnSalesRepIDChanging(string value);
    partial void OnSalesRepIDChanged();
    partial void OnSalesRepEmailIDChanging(string value);
    partial void OnSalesRepEmailIDChanged();
    partial void OnSalesRepUserNameChanging(string value);
    partial void OnSalesRepUserNameChanged();
    partial void OnRegionNameChanging(string value);
    partial void OnRegionNameChanged();
    partial void OnMemberEmailIDChanging(string value);
    partial void OnMemberEmailIDChanged();
    partial void OnIsQuietZoneBuilderChanging(char value);
    partial void OnIsQuietZoneBuilderChanged();
    partial void OnPlatinum_Pride_AwardChanging(char value);
    partial void OnPlatinum_Pride_AwardChanged();
    partial void OnTop_Of_The_House_CertifiedChanging(char value);
    partial void OnTop_Of_The_House_CertifiedChanged();
    partial void OnGreen_PledgeChanging(char value);
    partial void OnGreen_PledgeChanged();
    partial void OnRewardsLevelChanging(System.Nullable<int> value);
    partial void OnRewardsLevelChanged();
    partial void OnTotal_Protection_Rfg_SystemChanging(char value);
    partial void OnTotal_Protection_Rfg_SystemChanged();
    #endregion
		
		public RawBMContractor()
		{
			this._RawBMContractorTypes = new EntitySet<RawBMContractorType>(new Action<RawBMContractorType>(this.attach_RawBMContractorTypes), new Action<RawBMContractorType>(this.detach_RawBMContractorTypes));
			this._RawBMContractorInfo = default(EntityRef<RawBMContractorInfo>);
			this._RawBMLocation = default(EntityRef<RawBMLocation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="VarChar(20)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					if (this._RawBMLocation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnzipChanging(value);
					this.SendPropertyChanging();
					this._zip = value;
					this.SendPropertyChanged("zip");
					this.OnzipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address1", DbType="VarChar(128)")]
		public string address1
		{
			get
			{
				return this._address1;
			}
			set
			{
				if ((this._address1 != value))
				{
					this.Onaddress1Changing(value);
					this.SendPropertyChanging();
					this._address1 = value;
					this.SendPropertyChanged("address1");
					this.Onaddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address2", DbType="VarChar(128)")]
		public string address2
		{
			get
			{
				return this._address2;
			}
			set
			{
				if ((this._address2 != value))
				{
					this.Onaddress2Changing(value);
					this.SendPropertyChanging();
					this._address2 = value;
					this.SendPropertyChanged("address2");
					this.Onaddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(80)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(2)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone2", DbType="VarChar(20)")]
		public string phone2
		{
			get
			{
				return this._phone2;
			}
			set
			{
				if ((this._phone2 != value))
				{
					this.Onphone2Changing(value);
					this.SendPropertyChanging();
					this._phone2 = value;
					this.SendPropertyChanged("phone2");
					this.Onphone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_store", DbType="VarChar(128)")]
		public string store
		{
			get
			{
				return this._store;
			}
			set
			{
				if ((this._store != value))
				{
					this.OnstoreChanging(value);
					this.SendPropertyChanging();
					this._store = value;
					this.SendPropertyChanged("store");
					this.OnstoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pp_id", DbType="Int")]
		public System.Nullable<int> pp_id
		{
			get
			{
				return this._pp_id;
			}
			set
			{
				if ((this._pp_id != value))
				{
					if (this._RawBMContractorInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpp_idChanging(value);
					this.SendPropertyChanging();
					this._pp_id = value;
					this.SendPropertyChanged("pp_id");
					this.Onpp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="VarChar(8)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tradearea", DbType="Int")]
		public System.Nullable<int> tradearea
		{
			get
			{
				return this._tradearea;
			}
			set
			{
				if ((this._tradearea != value))
				{
					this.OntradeareaChanging(value);
					this.SendPropertyChanging();
					this._tradearea = value;
					this.SendPropertyChanged("tradearea");
					this.OntradeareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salesrep", DbType="VarChar(32)")]
		public string salesrep
		{
			get
			{
				return this._salesrep;
			}
			set
			{
				if ((this._salesrep != value))
				{
					this.OnsalesrepChanging(value);
					this.SendPropertyChanging();
					this._salesrep = value;
					this.SendPropertyChanged("salesrep");
					this.OnsalesrepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact", DbType="VarChar(32)")]
		public string contact
		{
			get
			{
				return this._contact;
			}
			set
			{
				if ((this._contact != value))
				{
					this.OncontactChanging(value);
					this.SendPropertyChanging();
					this._contact = value;
					this.SendPropertyChanged("contact");
					this.OncontactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProConnectFlag", DbType="Bit NOT NULL")]
		public bool ProConnectFlag
		{
			get
			{
				return this._ProConnectFlag;
			}
			set
			{
				if ((this._ProConnectFlag != value))
				{
					this.OnProConnectFlagChanging(value);
					this.SendPropertyChanging();
					this._ProConnectFlag = value;
					this.SendPropertyChanged("ProConnectFlag");
					this.OnProConnectFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_showroom", DbType="Bit NOT NULL")]
		public bool showroom
		{
			get
			{
				return this._showroom;
			}
			set
			{
				if ((this._showroom != value))
				{
					this.OnshowroomChanging(value);
					this.SendPropertyChanging();
					this._showroom = value;
					this.SendPropertyChanged("showroom");
					this.OnshowroomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctitle", DbType="VarChar(32)")]
		public string ctitle
		{
			get
			{
				return this._ctitle;
			}
			set
			{
				if ((this._ctitle != value))
				{
					this.OnctitleChanging(value);
					this.SendPropertyChanging();
					this._ctitle = value;
					this.SendPropertyChanged("ctitle");
					this.OnctitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="VarChar(100)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerType", DbType="VarChar(1)")]
		public System.Nullable<char> DealerType
		{
			get
			{
				return this._DealerType;
			}
			set
			{
				if ((this._DealerType != value))
				{
					this.OnDealerTypeChanging(value);
					this.SendPropertyChanging();
					this._DealerType = value;
					this.SendPropertyChanged("DealerType");
					this.OnDealerTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedDate
		{
			get
			{
				return this._UpdatedDate;
			}
			set
			{
				if ((this._UpdatedDate != value))
				{
					this.OnUpdatedDateChanging(value);
					this.SendPropertyChanging();
					this._UpdatedDate = value;
					this.SendPropertyChanged("UpdatedDate");
					this.OnUpdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebVisible", DbType="VarChar(1) NOT NULL")]
		public char WebVisible
		{
			get
			{
				return this._WebVisible;
			}
			set
			{
				if ((this._WebVisible != value))
				{
					this.OnWebVisibleChanging(value);
					this.SendPropertyChanging();
					this._WebVisible = value;
					this.SendPropertyChanged("WebVisible");
					this.OnWebVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPreferredPlat", DbType="VarChar(1) NOT NULL")]
		public char IsPreferredPlat
		{
			get
			{
				return this._IsPreferredPlat;
			}
			set
			{
				if ((this._IsPreferredPlat != value))
				{
					this.OnIsPreferredPlatChanging(value);
					this.SendPropertyChanging();
					this._IsPreferredPlat = value;
					this.SendPropertyChanged("IsPreferredPlat");
					this.OnIsPreferredPlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsExFxCertified", DbType="VarChar(1) NOT NULL")]
		public char IsExFxCertified
		{
			get
			{
				return this._IsExFxCertified;
			}
			set
			{
				if ((this._IsExFxCertified != value))
				{
					this.OnIsExFxCertifiedChanging(value);
					this.SendPropertyChanging();
					this._IsExFxCertified = value;
					this.SendPropertyChanged("IsExFxCertified");
					this.OnIsExFxCertifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPreferredPride", DbType="VarChar(1) NOT NULL")]
		public char IsPreferredPride
		{
			get
			{
				return this._IsPreferredPride;
			}
			set
			{
				if ((this._IsPreferredPride != value))
				{
					this.OnIsPreferredPrideChanging(value);
					this.SendPropertyChanging();
					this._IsPreferredPride = value;
					this.SendPropertyChanged("IsPreferredPride");
					this.OnIsPreferredPrideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesRepFirstName", DbType="VarChar(32)")]
		public string SalesRepFirstName
		{
			get
			{
				return this._SalesRepFirstName;
			}
			set
			{
				if ((this._SalesRepFirstName != value))
				{
					this.OnSalesRepFirstNameChanging(value);
					this.SendPropertyChanging();
					this._SalesRepFirstName = value;
					this.SendPropertyChanged("SalesRepFirstName");
					this.OnSalesRepFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesRepID", DbType="VarChar(10)")]
		public string SalesRepID
		{
			get
			{
				return this._SalesRepID;
			}
			set
			{
				if ((this._SalesRepID != value))
				{
					this.OnSalesRepIDChanging(value);
					this.SendPropertyChanging();
					this._SalesRepID = value;
					this.SendPropertyChanged("SalesRepID");
					this.OnSalesRepIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesRepEmailID", DbType="VarChar(100)")]
		public string SalesRepEmailID
		{
			get
			{
				return this._SalesRepEmailID;
			}
			set
			{
				if ((this._SalesRepEmailID != value))
				{
					this.OnSalesRepEmailIDChanging(value);
					this.SendPropertyChanging();
					this._SalesRepEmailID = value;
					this.SendPropertyChanged("SalesRepEmailID");
					this.OnSalesRepEmailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesRepUserName", DbType="VarChar(32)")]
		public string SalesRepUserName
		{
			get
			{
				return this._SalesRepUserName;
			}
			set
			{
				if ((this._SalesRepUserName != value))
				{
					this.OnSalesRepUserNameChanging(value);
					this.SendPropertyChanging();
					this._SalesRepUserName = value;
					this.SendPropertyChanged("SalesRepUserName");
					this.OnSalesRepUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionName", DbType="VarChar(50)")]
		public string RegionName
		{
			get
			{
				return this._RegionName;
			}
			set
			{
				if ((this._RegionName != value))
				{
					this.OnRegionNameChanging(value);
					this.SendPropertyChanging();
					this._RegionName = value;
					this.SendPropertyChanged("RegionName");
					this.OnRegionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberEmailID", DbType="VarChar(150)")]
		public string MemberEmailID
		{
			get
			{
				return this._MemberEmailID;
			}
			set
			{
				if ((this._MemberEmailID != value))
				{
					this.OnMemberEmailIDChanging(value);
					this.SendPropertyChanging();
					this._MemberEmailID = value;
					this.SendPropertyChanged("MemberEmailID");
					this.OnMemberEmailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsQuietZoneBuilder", DbType="VarChar(1) NOT NULL")]
		public char IsQuietZoneBuilder
		{
			get
			{
				return this._IsQuietZoneBuilder;
			}
			set
			{
				if ((this._IsQuietZoneBuilder != value))
				{
					this.OnIsQuietZoneBuilderChanging(value);
					this.SendPropertyChanging();
					this._IsQuietZoneBuilder = value;
					this.SendPropertyChanged("IsQuietZoneBuilder");
					this.OnIsQuietZoneBuilderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Platinum_Pride_Award", DbType="VarChar(1) NOT NULL")]
		public char Platinum_Pride_Award
		{
			get
			{
				return this._Platinum_Pride_Award;
			}
			set
			{
				if ((this._Platinum_Pride_Award != value))
				{
					this.OnPlatinum_Pride_AwardChanging(value);
					this.SendPropertyChanging();
					this._Platinum_Pride_Award = value;
					this.SendPropertyChanged("Platinum_Pride_Award");
					this.OnPlatinum_Pride_AwardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Top_Of_The_House_Certified", DbType="VarChar(1) NOT NULL")]
		public char Top_Of_The_House_Certified
		{
			get
			{
				return this._Top_Of_The_House_Certified;
			}
			set
			{
				if ((this._Top_Of_The_House_Certified != value))
				{
					this.OnTop_Of_The_House_CertifiedChanging(value);
					this.SendPropertyChanging();
					this._Top_Of_The_House_Certified = value;
					this.SendPropertyChanged("Top_Of_The_House_Certified");
					this.OnTop_Of_The_House_CertifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Green_Pledge", DbType="Char(1) NOT NULL")]
		public char Green_Pledge
		{
			get
			{
				return this._Green_Pledge;
			}
			set
			{
				if ((this._Green_Pledge != value))
				{
					this.OnGreen_PledgeChanging(value);
					this.SendPropertyChanging();
					this._Green_Pledge = value;
					this.SendPropertyChanged("Green_Pledge");
					this.OnGreen_PledgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RewardsLevel", DbType="INT")]
		public System.Nullable<int> RewardsLevel
		{
			get
			{
				return this._RewardsLevel;
			}
			set
			{
				if ((this._RewardsLevel != value))
				{
					this.OnRewardsLevelChanging(value);
					this.SendPropertyChanging();
					this._RewardsLevel = value;
					this.SendPropertyChanged("RewardsLevel");
					this.OnRewardsLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Protection_Rfg_System", DbType="Char(1) NOT NULL")]
		public char Total_Protection_Rfg_System
		{
			get
			{
				return this._Total_Protection_Rfg_System;
			}
			set
			{
				if ((this._Total_Protection_Rfg_System != value))
				{
					this.OnTotal_Protection_Rfg_SystemChanging(value);
					this.SendPropertyChanging();
					this._Total_Protection_Rfg_System = value;
					this.SendPropertyChanged("Total_Protection_Rfg_System");
					this.OnTotal_Protection_Rfg_SystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RawBMContractor_RawBMContractorType", Storage="_RawBMContractorTypes", ThisKey="id", OtherKey="dealer_id")]
		public EntitySet<RawBMContractorType> RawBMContractorTypes
		{
			get
			{
				return this._RawBMContractorTypes;
			}
			set
			{
				this._RawBMContractorTypes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RawBMContractorInfo_RawBMContractor", Storage="_RawBMContractorInfo", ThisKey="pp_id", OtherKey="id", IsForeignKey=true)]
		public RawBMContractorInfo RawBMContractorInfo
		{
			get
			{
				return this._RawBMContractorInfo.Entity;
			}
			set
			{
				RawBMContractorInfo previousValue = this._RawBMContractorInfo.Entity;
				if (((previousValue != value) 
							|| (this._RawBMContractorInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RawBMContractorInfo.Entity = null;
						previousValue.RawBMContractors.Remove(this);
					}
					this._RawBMContractorInfo.Entity = value;
					if ((value != null))
					{
						value.RawBMContractors.Add(this);
						this._pp_id = value.id;
					}
					else
					{
						this._pp_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("RawBMContractorInfo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RawBMLocation_RawBMContractor", Storage="_RawBMLocation", ThisKey="zip", OtherKey="PostalCode", IsForeignKey=true)]
		public RawBMLocation RawBMLocation
		{
			get
			{
				return this._RawBMLocation.Entity;
			}
			set
			{
				RawBMLocation previousValue = this._RawBMLocation.Entity;
				if (((previousValue != value) 
							|| (this._RawBMLocation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RawBMLocation.Entity = null;
						previousValue.RawBMContractors.Remove(this);
					}
					this._RawBMLocation.Entity = value;
					if ((value != null))
					{
						value.RawBMContractors.Add(this);
						this._zip = value.PostalCode;
					}
					else
					{
						this._zip = default(string);
					}
					this.SendPropertyChanged("RawBMLocation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RawBMContractorTypes(RawBMContractorType entity)
		{
			this.SendPropertyChanging();
			entity.RawBMContractor = this;
		}
		
		private void detach_RawBMContractorTypes(RawBMContractorType entity)
		{
			this.SendPropertyChanging();
			entity.RawBMContractor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pinkpages")]
	public partial class RawBMContractorInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private bool _status;
		
		private string _name;
		
		private string _url;
		
		private bool _photo_active;
		
		private bool _photo_align;
		
		private bool _logo_active;
		
		private bool _logo_align;
		
		private string _description;
		
		private bool _logo_gif;
		
		private bool _photo_gif;
		
		private string _address;
		
		private string _hours;
		
		private bool _builder_alliance;
		
		private System.Nullable<char> _DealerType;
		
		private EntitySet<RawBMContractor> _RawBMContractors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(bool value);
    partial void OnstatusChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void Onphoto_activeChanging(bool value);
    partial void Onphoto_activeChanged();
    partial void Onphoto_alignChanging(bool value);
    partial void Onphoto_alignChanged();
    partial void Onlogo_activeChanging(bool value);
    partial void Onlogo_activeChanged();
    partial void Onlogo_alignChanging(bool value);
    partial void Onlogo_alignChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onlogo_gifChanging(bool value);
    partial void Onlogo_gifChanged();
    partial void Onphoto_gifChanging(bool value);
    partial void Onphoto_gifChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnhoursChanging(string value);
    partial void OnhoursChanged();
    partial void Onbuilder_allianceChanging(bool value);
    partial void Onbuilder_allianceChanged();
    partial void OnDealerTypeChanging(System.Nullable<char> value);
    partial void OnDealerTypeChanged();
    #endregion
		
		public RawBMContractorInfo()
		{
			this._RawBMContractors = new EntitySet<RawBMContractor>(new Action<RawBMContractor>(this.attach_RawBMContractors), new Action<RawBMContractor>(this.detach_RawBMContractors));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit NOT NULL")]
		public bool status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="VarChar(255)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo_active", DbType="Bit NOT NULL")]
		public bool photo_active
		{
			get
			{
				return this._photo_active;
			}
			set
			{
				if ((this._photo_active != value))
				{
					this.Onphoto_activeChanging(value);
					this.SendPropertyChanging();
					this._photo_active = value;
					this.SendPropertyChanged("photo_active");
					this.Onphoto_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo_align", DbType="Bit NOT NULL")]
		public bool photo_align
		{
			get
			{
				return this._photo_align;
			}
			set
			{
				if ((this._photo_align != value))
				{
					this.Onphoto_alignChanging(value);
					this.SendPropertyChanging();
					this._photo_align = value;
					this.SendPropertyChanged("photo_align");
					this.Onphoto_alignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo_active", DbType="Bit NOT NULL")]
		public bool logo_active
		{
			get
			{
				return this._logo_active;
			}
			set
			{
				if ((this._logo_active != value))
				{
					this.Onlogo_activeChanging(value);
					this.SendPropertyChanging();
					this._logo_active = value;
					this.SendPropertyChanged("logo_active");
					this.Onlogo_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo_align", DbType="Bit NOT NULL")]
		public bool logo_align
		{
			get
			{
				return this._logo_align;
			}
			set
			{
				if ((this._logo_align != value))
				{
					this.Onlogo_alignChanging(value);
					this.SendPropertyChanging();
					this._logo_align = value;
					this.SendPropertyChanged("logo_align");
					this.Onlogo_alignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo_gif", DbType="Bit NOT NULL")]
		public bool logo_gif
		{
			get
			{
				return this._logo_gif;
			}
			set
			{
				if ((this._logo_gif != value))
				{
					this.Onlogo_gifChanging(value);
					this.SendPropertyChanging();
					this._logo_gif = value;
					this.SendPropertyChanged("logo_gif");
					this.Onlogo_gifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo_gif", DbType="Bit NOT NULL")]
		public bool photo_gif
		{
			get
			{
				return this._photo_gif;
			}
			set
			{
				if ((this._photo_gif != value))
				{
					this.Onphoto_gifChanging(value);
					this.SendPropertyChanging();
					this._photo_gif = value;
					this.SendPropertyChanged("photo_gif");
					this.Onphoto_gifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(255)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hours", DbType="VarChar(255)")]
		public string hours
		{
			get
			{
				return this._hours;
			}
			set
			{
				if ((this._hours != value))
				{
					this.OnhoursChanging(value);
					this.SendPropertyChanging();
					this._hours = value;
					this.SendPropertyChanged("hours");
					this.OnhoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_builder_alliance", DbType="Bit NOT NULL")]
		public bool builder_alliance
		{
			get
			{
				return this._builder_alliance;
			}
			set
			{
				if ((this._builder_alliance != value))
				{
					this.Onbuilder_allianceChanging(value);
					this.SendPropertyChanging();
					this._builder_alliance = value;
					this.SendPropertyChanged("builder_alliance");
					this.Onbuilder_allianceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerType", DbType="VarChar(1)")]
		public System.Nullable<char> DealerType
		{
			get
			{
				return this._DealerType;
			}
			set
			{
				if ((this._DealerType != value))
				{
					this.OnDealerTypeChanging(value);
					this.SendPropertyChanging();
					this._DealerType = value;
					this.SendPropertyChanged("DealerType");
					this.OnDealerTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RawBMContractorInfo_RawBMContractor", Storage="_RawBMContractors", ThisKey="id", OtherKey="pp_id")]
		public EntitySet<RawBMContractor> RawBMContractors
		{
			get
			{
				return this._RawBMContractors;
			}
			set
			{
				this._RawBMContractors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RawBMContractors(RawBMContractor entity)
		{
			this.SendPropertyChanging();
			entity.RawBMContractorInfo = this;
		}
		
		private void detach_RawBMContractors(RawBMContractor entity)
		{
			this.SendPropertyChanging();
			entity.RawBMContractorInfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dealer_zipcodes")]
	public partial class RawBMLocation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _PostalCode;
		
		private System.Nullable<double> _Longitude;
		
		private System.Nullable<double> _Latitude;
		
		private EntitySet<RawBMContractor> _RawBMContractors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnPostalCodeChanging(string value);
    partial void OnPostalCodeChanged();
    partial void OnLongitudeChanging(System.Nullable<double> value);
    partial void OnLongitudeChanged();
    partial void OnLatitudeChanging(System.Nullable<double> value);
    partial void OnLatitudeChanged();
    #endregion
		
		public RawBMLocation()
		{
			this._RawBMContractors = new EntitySet<RawBMContractor>(new Action<RawBMContractor>(this.attach_RawBMContractors), new Action<RawBMContractor>(this.detach_RawBMContractors));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="zipcode", Storage="_PostalCode", DbType="VarChar(5)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this.OnPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._PostalCode = value;
					this.SendPropertyChanged("PostalCode");
					this.OnPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="longitude", Storage="_Longitude", DbType="Float")]
		public System.Nullable<double> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="latitude", Storage="_Latitude", DbType="Float")]
		public System.Nullable<double> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RawBMLocation_RawBMContractor", Storage="_RawBMContractors", ThisKey="PostalCode", OtherKey="zip")]
		public EntitySet<RawBMContractor> RawBMContractors
		{
			get
			{
				return this._RawBMContractors;
			}
			set
			{
				this._RawBMContractors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RawBMContractors(RawBMContractor entity)
		{
			this.SendPropertyChanging();
			entity.RawBMLocation = this;
		}
		
		private void detach_RawBMContractors(RawBMContractor entity)
		{
			this.SendPropertyChanging();
			entity.RawBMLocation = null;
		}
	}
}
#pragma warning restore 1591
