#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.ocwebservice.locator.data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OWC_DealerLocator")]
	public partial class DealerLocatorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRawCanadaBMDealer(com.ocwebservice.locator.model.RawCanadaBMDealer instance);
    partial void UpdateRawCanadaBMDealer(com.ocwebservice.locator.model.RawCanadaBMDealer instance);
    partial void DeleteRawCanadaBMDealer(com.ocwebservice.locator.model.RawCanadaBMDealer instance);
    partial void InsertRawBMDealer(com.ocwebservice.locator.model.RawBMDealer instance);
    partial void UpdateRawBMDealer(com.ocwebservice.locator.model.RawBMDealer instance);
    partial void DeleteRawBMDealer(com.ocwebservice.locator.model.RawBMDealer instance);
    #endregion
		
		public DealerLocatorDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OwensCorning.Locator.DealerLocator"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DealerLocatorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DealerLocatorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DealerLocatorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DealerLocatorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<com.ocwebservice.locator.model.RawCanadaBMDealer> RawCanadaBMDealers
		{
			get
			{
				return this.GetTable<com.ocwebservice.locator.model.RawCanadaBMDealer>();
			}
		}
		
		public System.Data.Linq.Table<com.ocwebservice.locator.model.RawBMDealer> RawBMDealers
		{
			get
			{
				return this.GetTable<com.ocwebservice.locator.model.RawBMDealer>();
			}
		}
		
		public System.Data.Linq.Table<com.ocwebservice.locator.model.RawBMDealerLocation> RawBMDealerLocations
		{
			get
			{
				return this.GetTable<com.ocwebservice.locator.model.RawBMDealerLocation>();
			}
		}
	}
}
namespace com.ocwebservice.locator.model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CanadaDealersInfo")]
	public partial class RawCanadaBMDealer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private string _product;
		
		private string _company;
		
		private string _address;
		
		private string _city;
		
		private string _province;
		
		private string _postal_code;
		
		private string _country;
		
		private string _phone;
		
		private System.DateTime _ts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnproductChanging(string value);
    partial void OnproductChanged();
    partial void OncompanyChanging(string value);
    partial void OncompanyChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void Onpostal_codeChanging(string value);
    partial void Onpostal_codeChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OntsChanging(System.DateTime value);
    partial void OntsChanged();
    #endregion
		
		public RawCanadaBMDealer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(10,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product", DbType="NVarChar(128)")]
		public string product
		{
			get
			{
				return this._product;
			}
			set
			{
				if ((this._product != value))
				{
					this.OnproductChanging(value);
					this.SendPropertyChanging();
					this._product = value;
					this.SendPropertyChanged("product");
					this.OnproductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="NVarChar(128)")]
		public string company
		{
			get
			{
				return this._company;
			}
			set
			{
				if ((this._company != value))
				{
					this.OncompanyChanging(value);
					this.SendPropertyChanging();
					this._company = value;
					this.SendPropertyChanged("company");
					this.OncompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(128)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(64)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="NVarChar(2)")]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postal_code", DbType="VarChar(10)")]
		public string postal_code
		{
			get
			{
				return this._postal_code;
			}
			set
			{
				if ((this._postal_code != value))
				{
					this.Onpostal_codeChanging(value);
					this.SendPropertyChanging();
					this._postal_code = value;
					this.SendPropertyChanged("postal_code");
					this.Onpostal_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(64)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts", DbType="DateTime NOT NULL")]
		public System.DateTime ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				if ((this._ts != value))
				{
					this.OntsChanging(value);
					this.SendPropertyChanging();
					this._ts = value;
					this.SendPropertyChanged("ts");
					this.OntsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_DealerInfo_Chain")]
	public partial class RawBMDealer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private string _RecordID;
		
		private string _StoreName;
		
		private string _Address;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _Country;
		
		private string _Phone;
		
		private System.Nullable<bool> _StocksFiberGlassInsulation;
		
		private System.Nullable<bool> _StocksFoamInsulation;
		
		private System.Nullable<bool> _StocksVinylSiding;
		
		private System.Nullable<bool> _StocksRoofing;
		
		private System.Nullable<bool> _StocksHousewrap;
		
		private System.Nullable<bool> _StocksAttiCat;
		
		private string _WebSiteAddress;
		
		private System.Nullable<bool> _SellsToDIY;
		
		private System.Nullable<bool> _SellsToContractors;
		
		private string _SourceDB;
		
		private string _RecordOwner;
		
		private string _RecordOwnerEmail;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private System.Nullable<System.DateTime> _DateUpdated;
		
		private System.Nullable<System.DateTime> _DateUploaded;
		
		private string _ChainName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnRecordIDChanging(string value);
    partial void OnRecordIDChanged();
    partial void OnStoreNameChanging(string value);
    partial void OnStoreNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnStocksFiberGlassInsulationChanging(System.Nullable<bool> value);
    partial void OnStocksFiberGlassInsulationChanged();
    partial void OnStocksFoamInsulationChanging(System.Nullable<bool> value);
    partial void OnStocksFoamInsulationChanged();
    partial void OnStocksVinylSidingChanging(System.Nullable<bool> value);
    partial void OnStocksVinylSidingChanged();
    partial void OnStocksRoofingChanging(System.Nullable<bool> value);
    partial void OnStocksRoofingChanged();
    partial void OnStocksHousewrapChanging(System.Nullable<bool> value);
    partial void OnStocksHousewrapChanged();
    partial void OnStocksAttiCatChanging(System.Nullable<bool> value);
    partial void OnStocksAttiCatChanged();
    partial void OnWebSiteAddressChanging(string value);
    partial void OnWebSiteAddressChanged();
    partial void OnSellsToDIYChanging(System.Nullable<bool> value);
    partial void OnSellsToDIYChanged();
    partial void OnSellsToContractorsChanging(System.Nullable<bool> value);
    partial void OnSellsToContractorsChanged();
    partial void OnSourceDBChanging(string value);
    partial void OnSourceDBChanged();
    partial void OnRecordOwnerChanging(string value);
    partial void OnRecordOwnerChanged();
    partial void OnRecordOwnerEmailChanging(string value);
    partial void OnRecordOwnerEmailChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnDateUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateUpdatedChanged();
    partial void OnDateUploadedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateUploadedChanged();
    partial void OnChainNameChanging(string value);
    partial void OnChainNameChanged();
    #endregion
		
		public RawBMDealer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(10,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="VarChar(10)")]
		public string RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreName", DbType="VarChar(50)")]
		public string StoreName
		{
			get
			{
				return this._StoreName;
			}
			set
			{
				if ((this._StoreName != value))
				{
					this.OnStoreNameChanging(value);
					this.SendPropertyChanging();
					this._StoreName = value;
					this.SendPropertyChanged("StoreName");
					this.OnStoreNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(10)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(15)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(50)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StocksFiberGlassInsulation", DbType="Bit")]
		public System.Nullable<bool> StocksFiberGlassInsulation
		{
			get
			{
				return this._StocksFiberGlassInsulation;
			}
			set
			{
				if ((this._StocksFiberGlassInsulation != value))
				{
					this.OnStocksFiberGlassInsulationChanging(value);
					this.SendPropertyChanging();
					this._StocksFiberGlassInsulation = value;
					this.SendPropertyChanged("StocksFiberGlassInsulation");
					this.OnStocksFiberGlassInsulationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StocksFoamInsulation", DbType="Bit")]
		public System.Nullable<bool> StocksFoamInsulation
		{
			get
			{
				return this._StocksFoamInsulation;
			}
			set
			{
				if ((this._StocksFoamInsulation != value))
				{
					this.OnStocksFoamInsulationChanging(value);
					this.SendPropertyChanging();
					this._StocksFoamInsulation = value;
					this.SendPropertyChanged("StocksFoamInsulation");
					this.OnStocksFoamInsulationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StocksVinylSiding", DbType="Bit")]
		public System.Nullable<bool> StocksVinylSiding
		{
			get
			{
				return this._StocksVinylSiding;
			}
			set
			{
				if ((this._StocksVinylSiding != value))
				{
					this.OnStocksVinylSidingChanging(value);
					this.SendPropertyChanging();
					this._StocksVinylSiding = value;
					this.SendPropertyChanged("StocksVinylSiding");
					this.OnStocksVinylSidingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StocksRoofing", DbType="Bit")]
		public System.Nullable<bool> StocksRoofing
		{
			get
			{
				return this._StocksRoofing;
			}
			set
			{
				if ((this._StocksRoofing != value))
				{
					this.OnStocksRoofingChanging(value);
					this.SendPropertyChanging();
					this._StocksRoofing = value;
					this.SendPropertyChanged("StocksRoofing");
					this.OnStocksRoofingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StocksHousewrap", DbType="Bit")]
		public System.Nullable<bool> StocksHousewrap
		{
			get
			{
				return this._StocksHousewrap;
			}
			set
			{
				if ((this._StocksHousewrap != value))
				{
					this.OnStocksHousewrapChanging(value);
					this.SendPropertyChanging();
					this._StocksHousewrap = value;
					this.SendPropertyChanged("StocksHousewrap");
					this.OnStocksHousewrapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StocksAttiCat", DbType="Bit")]
		public System.Nullable<bool> StocksAttiCat
		{
			get
			{
				return this._StocksAttiCat;
			}
			set
			{
				if ((this._StocksAttiCat != value))
				{
					this.OnStocksAttiCatChanging(value);
					this.SendPropertyChanging();
					this._StocksAttiCat = value;
					this.SendPropertyChanged("StocksAttiCat");
					this.OnStocksAttiCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebSiteAddress", DbType="VarChar(255)")]
		public string WebSiteAddress
		{
			get
			{
				return this._WebSiteAddress;
			}
			set
			{
				if ((this._WebSiteAddress != value))
				{
					this.OnWebSiteAddressChanging(value);
					this.SendPropertyChanging();
					this._WebSiteAddress = value;
					this.SendPropertyChanged("WebSiteAddress");
					this.OnWebSiteAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellsToDIY", DbType="Bit")]
		public System.Nullable<bool> SellsToDIY
		{
			get
			{
				return this._SellsToDIY;
			}
			set
			{
				if ((this._SellsToDIY != value))
				{
					this.OnSellsToDIYChanging(value);
					this.SendPropertyChanging();
					this._SellsToDIY = value;
					this.SendPropertyChanged("SellsToDIY");
					this.OnSellsToDIYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellsToContractors", DbType="Bit")]
		public System.Nullable<bool> SellsToContractors
		{
			get
			{
				return this._SellsToContractors;
			}
			set
			{
				if ((this._SellsToContractors != value))
				{
					this.OnSellsToContractorsChanging(value);
					this.SendPropertyChanging();
					this._SellsToContractors = value;
					this.SendPropertyChanged("SellsToContractors");
					this.OnSellsToContractorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceDB", DbType="VarChar(50)")]
		public string SourceDB
		{
			get
			{
				return this._SourceDB;
			}
			set
			{
				if ((this._SourceDB != value))
				{
					this.OnSourceDBChanging(value);
					this.SendPropertyChanging();
					this._SourceDB = value;
					this.SendPropertyChanged("SourceDB");
					this.OnSourceDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordOwner", DbType="VarChar(50)")]
		public string RecordOwner
		{
			get
			{
				return this._RecordOwner;
			}
			set
			{
				if ((this._RecordOwner != value))
				{
					this.OnRecordOwnerChanging(value);
					this.SendPropertyChanging();
					this._RecordOwner = value;
					this.SendPropertyChanged("RecordOwner");
					this.OnRecordOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordOwnerEmail", DbType="VarChar(50)")]
		public string RecordOwnerEmail
		{
			get
			{
				return this._RecordOwnerEmail;
			}
			set
			{
				if ((this._RecordOwnerEmail != value))
				{
					this.OnRecordOwnerEmailChanging(value);
					this.SendPropertyChanging();
					this._RecordOwnerEmail = value;
					this.SendPropertyChanged("RecordOwnerEmail");
					this.OnRecordOwnerEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUpdated
		{
			get
			{
				return this._DateUpdated;
			}
			set
			{
				if ((this._DateUpdated != value))
				{
					this.OnDateUpdatedChanging(value);
					this.SendPropertyChanging();
					this._DateUpdated = value;
					this.SendPropertyChanged("DateUpdated");
					this.OnDateUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUploaded", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUploaded
		{
			get
			{
				return this._DateUploaded;
			}
			set
			{
				if ((this._DateUploaded != value))
				{
					this.OnDateUploadedChanging(value);
					this.SendPropertyChanging();
					this._DateUploaded = value;
					this.SendPropertyChanged("DateUploaded");
					this.OnDateUploadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChainName", CanBeNull=false)]
		public string ChainName
		{
			get
			{
				return this._ChainName;
			}
			set
			{
				if ((this._ChainName != value))
				{
					this.OnChainNameChanging(value);
					this.SendPropertyChanging();
					this._ChainName = value;
					this.SendPropertyChanged("ChainName");
					this.OnChainNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RfgZips")]
	public partial class RawBMDealerLocation
	{
		
		private string _Zip;
		
		private string _DistCodeListID;
		
		private string _TradeArea;
		
		private string _TradeCodeListID;
		
		private string _St;
		
		private string _County;
		
		private string _City;
		
		private System.Nullable<double> _Lat;
		
		private System.Nullable<double> _Long;
		
		private System.Data.Linq.Binary _ts;
		
		public RawBMDealerLocation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="NVarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this._Zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistCodeListID", DbType="NVarChar(5) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DistCodeListID
		{
			get
			{
				return this._DistCodeListID;
			}
			set
			{
				if ((this._DistCodeListID != value))
				{
					this._DistCodeListID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeArea", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string TradeArea
		{
			get
			{
				return this._TradeArea;
			}
			set
			{
				if ((this._TradeArea != value))
				{
					this._TradeArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeCodeListID", DbType="NVarChar(5) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TradeCodeListID
		{
			get
			{
				return this._TradeCodeListID;
			}
			set
			{
				if ((this._TradeCodeListID != value))
				{
					this._TradeCodeListID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_St", DbType="NVarChar(3)", UpdateCheck=UpdateCheck.Never)]
		public string St
		{
			get
			{
				return this._St;
			}
			set
			{
				if ((this._St != value))
				{
					this._St = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_County", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string County
		{
			get
			{
				return this._County;
			}
			set
			{
				if ((this._County != value))
				{
					this._County = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this._Lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Long", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> Long
		{
			get
			{
				return this._Long;
			}
			set
			{
				if ((this._Long != value))
				{
					this._Long = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				if ((this._ts != value))
				{
					this._ts = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
