#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.ocwebservice.locator.data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OCCommon")]
	public partial class LocationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LocationDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OwensCorning.Common"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LocationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LocationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LocationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LocationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<com.ocwebservice.locator.model.Location> Locations
		{
			get
			{
				return this.GetTable<com.ocwebservice.locator.model.Location>();
			}
		}
	}
}
namespace com.ocwebservice.locator.model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZipPostalCodes")]
	public partial class Location
	{
		
		private string _CountryName;
		
		private string _PostalCode;
		
		private System.Nullable<char> _PostalType;
		
		private string _CityName;
		
		private System.Nullable<char> _CityType;
		
		private string _CountyName;
		
		private string _CountyFIPS;
		
		private string _ProvinceName;
		
		private string _ProvinceAbbr;
		
		private string _StateFIPS;
		
		private string _MSACode;
		
		private string _AreaCode;
		
		private string _TimeZone;
		
		private System.Nullable<decimal> _UTC;
		
		private System.Nullable<char> _DST;
		
		private System.Nullable<decimal> _Latitude;
		
		private System.Nullable<decimal> _Longitude;
		
		public Location()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryName", DbType="VarChar(12)")]
		public string CountryName
		{
			get
			{
				return this._CountryName;
			}
			set
			{
				if ((this._CountryName != value))
				{
					this._CountryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="VarChar(7)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this._PostalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalType", DbType="Char(1)")]
		public System.Nullable<char> PostalType
		{
			get
			{
				return this._PostalType;
			}
			set
			{
				if ((this._PostalType != value))
				{
					this._PostalType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityName", DbType="VarChar(64)")]
		public string CityName
		{
			get
			{
				return this._CityName;
			}
			set
			{
				if ((this._CityName != value))
				{
					this._CityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityType", DbType="Char(1)")]
		public System.Nullable<char> CityType
		{
			get
			{
				return this._CityType;
			}
			set
			{
				if ((this._CityType != value))
				{
					this._CityType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountyName", DbType="VarChar(64)")]
		public string CountyName
		{
			get
			{
				return this._CountyName;
			}
			set
			{
				if ((this._CountyName != value))
				{
					this._CountyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountyFIPS", DbType="Char(5)")]
		public string CountyFIPS
		{
			get
			{
				return this._CountyFIPS;
			}
			set
			{
				if ((this._CountyFIPS != value))
				{
					this._CountyFIPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceName", DbType="VarChar(64)")]
		public string ProvinceName
		{
			get
			{
				return this._ProvinceName;
			}
			set
			{
				if ((this._ProvinceName != value))
				{
					this._ProvinceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceAbbr", DbType="Char(2)")]
		public string ProvinceAbbr
		{
			get
			{
				return this._ProvinceAbbr;
			}
			set
			{
				if ((this._ProvinceAbbr != value))
				{
					this._ProvinceAbbr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateFIPS", DbType="Char(2)")]
		public string StateFIPS
		{
			get
			{
				return this._StateFIPS;
			}
			set
			{
				if ((this._StateFIPS != value))
				{
					this._StateFIPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSACode", DbType="Char(4)")]
		public string MSACode
		{
			get
			{
				return this._MSACode;
			}
			set
			{
				if ((this._MSACode != value))
				{
					this._MSACode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaCode", DbType="VarChar(16)")]
		public string AreaCode
		{
			get
			{
				return this._AreaCode;
			}
			set
			{
				if ((this._AreaCode != value))
				{
					this._AreaCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZone", DbType="VarChar(16)")]
		public string TimeZone
		{
			get
			{
				return this._TimeZone;
			}
			set
			{
				if ((this._TimeZone != value))
				{
					this._TimeZone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UTC", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> UTC
		{
			get
			{
				return this._UTC;
			}
			set
			{
				if ((this._UTC != value))
				{
					this._UTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DST", DbType="Char(1)")]
		public System.Nullable<char> DST
		{
			get
			{
				return this._DST;
			}
			set
			{
				if ((this._DST != value))
				{
					this._DST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
