#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwensCorning.ContactService.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="owc_owens")]
	public partial class ContactInformationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertoc_contactlist(oc_contactlist instance);
    partial void Updateoc_contactlist(oc_contactlist instance);
    partial void Deleteoc_contactlist(oc_contactlist instance);
    #endregion
		
		public ContactInformationDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["owc_owensConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ContactInformationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContactInformationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContactInformationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContactInformationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<oc_contactlist> oc_contactlists
		{
			get
			{
				return this.GetTable<oc_contactlist>();
			}
		}
		
		public System.Data.Linq.Table<ContactListNameMap> ContactListNameMaps
		{
			get
			{
				return this.GetTable<ContactListNameMap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oc_contactlist")]
	public partial class oc_contactlist : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pk_id;
		
		private System.DateTime _date_created;
		
		private string _business_area;
		
		private string _source_form_name;
		
		private string _source_form_path;
		
		private string _external_key;
		
		private System.Nullable<System.DateTime> _external_date;
		
		private string _contact_type;
		
		private string _contact_fullname;
		
		private string _contact_email;
		
		private string _contact_phone;
		
		private string _company_name;
		
		private string _language;
		
		private string _xml_form_data;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_idChanging(int value);
    partial void Onpk_idChanged();
    partial void Ondate_createdChanging(System.DateTime value);
    partial void Ondate_createdChanged();
    partial void Onbusiness_areaChanging(string value);
    partial void Onbusiness_areaChanged();
    partial void Onsource_form_nameChanging(string value);
    partial void Onsource_form_nameChanged();
    partial void Onsource_form_pathChanging(string value);
    partial void Onsource_form_pathChanged();
    partial void Onexternal_keyChanging(string value);
    partial void Onexternal_keyChanged();
    partial void Onexternal_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onexternal_dateChanged();
    partial void Oncontact_typeChanging(string value);
    partial void Oncontact_typeChanged();
    partial void Oncontact_fullnameChanging(string value);
    partial void Oncontact_fullnameChanged();
    partial void Oncontact_emailChanging(string value);
    partial void Oncontact_emailChanged();
    partial void Oncontact_phoneChanging(string value);
    partial void Oncontact_phoneChanged();
    partial void Oncompany_nameChanging(string value);
    partial void Oncompany_nameChanged();
    partial void OnlanguageChanging(string value);
    partial void OnlanguageChanged();
    partial void Onxml_form_dataChanging(string value);
    partial void Onxml_form_dataChanged();
    #endregion
		
		public oc_contactlist()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pk_id
		{
			get
			{
				return this._pk_id;
			}
			set
			{
				if ((this._pk_id != value))
				{
					this.Onpk_idChanging(value);
					this.SendPropertyChanging();
					this._pk_id = value;
					this.SendPropertyChanged("pk_id");
					this.Onpk_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_created", DbType="DateTime NOT NULL")]
		public System.DateTime date_created
		{
			get
			{
				return this._date_created;
			}
			set
			{
				if ((this._date_created != value))
				{
					this.Ondate_createdChanging(value);
					this.SendPropertyChanging();
					this._date_created = value;
					this.SendPropertyChanged("date_created");
					this.Ondate_createdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_business_area", DbType="NVarChar(50)")]
		public string business_area
		{
			get
			{
				return this._business_area;
			}
			set
			{
				if ((this._business_area != value))
				{
					this.Onbusiness_areaChanging(value);
					this.SendPropertyChanging();
					this._business_area = value;
					this.SendPropertyChanged("business_area");
					this.Onbusiness_areaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_form_name", DbType="NVarChar(255)")]
		public string source_form_name
		{
			get
			{
				return this._source_form_name;
			}
			set
			{
				if ((this._source_form_name != value))
				{
					this.Onsource_form_nameChanging(value);
					this.SendPropertyChanging();
					this._source_form_name = value;
					this.SendPropertyChanged("source_form_name");
					this.Onsource_form_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_form_path", DbType="NVarChar(768)")]
		public string source_form_path
		{
			get
			{
				return this._source_form_path;
			}
			set
			{
				if ((this._source_form_path != value))
				{
					this.Onsource_form_pathChanging(value);
					this.SendPropertyChanging();
					this._source_form_path = value;
					this.SendPropertyChanged("source_form_path");
					this.Onsource_form_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_external_key", DbType="NVarChar(50)")]
		public string external_key
		{
			get
			{
				return this._external_key;
			}
			set
			{
				if ((this._external_key != value))
				{
					this.Onexternal_keyChanging(value);
					this.SendPropertyChanging();
					this._external_key = value;
					this.SendPropertyChanged("external_key");
					this.Onexternal_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_external_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> external_date
		{
			get
			{
				return this._external_date;
			}
			set
			{
				if ((this._external_date != value))
				{
					this.Onexternal_dateChanging(value);
					this.SendPropertyChanging();
					this._external_date = value;
					this.SendPropertyChanged("external_date");
					this.Onexternal_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_type", DbType="NVarChar(255)")]
		public string contact_type
		{
			get
			{
				return this._contact_type;
			}
			set
			{
				if ((this._contact_type != value))
				{
					this.Oncontact_typeChanging(value);
					this.SendPropertyChanging();
					this._contact_type = value;
					this.SendPropertyChanged("contact_type");
					this.Oncontact_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_fullname", DbType="NVarChar(255)")]
		public string contact_fullname
		{
			get
			{
				return this._contact_fullname;
			}
			set
			{
				if ((this._contact_fullname != value))
				{
					this.Oncontact_fullnameChanging(value);
					this.SendPropertyChanging();
					this._contact_fullname = value;
					this.SendPropertyChanged("contact_fullname");
					this.Oncontact_fullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_email", DbType="NVarChar(255)")]
		public string contact_email
		{
			get
			{
				return this._contact_email;
			}
			set
			{
				if ((this._contact_email != value))
				{
					this.Oncontact_emailChanging(value);
					this.SendPropertyChanging();
					this._contact_email = value;
					this.SendPropertyChanged("contact_email");
					this.Oncontact_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_phone", DbType="VarChar(40)")]
		public string contact_phone
		{
			get
			{
				return this._contact_phone;
			}
			set
			{
				if ((this._contact_phone != value))
				{
					this.Oncontact_phoneChanging(value);
					this.SendPropertyChanging();
					this._contact_phone = value;
					this.SendPropertyChanged("contact_phone");
					this.Oncontact_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_name", DbType="NVarChar(80)")]
		public string company_name
		{
			get
			{
				return this._company_name;
			}
			set
			{
				if ((this._company_name != value))
				{
					this.Oncompany_nameChanging(value);
					this.SendPropertyChanging();
					this._company_name = value;
					this.SendPropertyChanged("company_name");
					this.Oncompany_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_language", DbType="Char(2)")]
		public string language
		{
			get
			{
				return this._language;
			}
			set
			{
				if ((this._language != value))
				{
					this.OnlanguageChanging(value);
					this.SendPropertyChanging();
					this._language = value;
					this.SendPropertyChanged("language");
					this.OnlanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xml_form_data", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string xml_form_data
		{
			get
			{
				return this._xml_form_data;
			}
			set
			{
				if ((this._xml_form_data != value))
				{
					this.Onxml_form_dataChanging(value);
					this.SendPropertyChanging();
					this._xml_form_data = value;
					this.SendPropertyChanged("xml_form_data");
					this.Onxml_form_dataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ContactListNameMap")]
	public partial class ContactListNameMap
	{
		
		private string _SourceFormName;
		
		private string _Name;
		
		private bool _Active;
		
		private string _BusinessName;
		
		private string _ColumnMap;
		
		public ContactListNameMap()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceFormName", CanBeNull=false)]
		public string SourceFormName
		{
			get
			{
				return this._SourceFormName;
			}
			set
			{
				if ((this._SourceFormName != value))
				{
					this._SourceFormName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessName", CanBeNull=false)]
		public string BusinessName
		{
			get
			{
				return this._BusinessName;
			}
			set
			{
				if ((this._BusinessName != value))
				{
					this._BusinessName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnMap", CanBeNull=false)]
		public string ColumnMap
		{
			get
			{
				return this._ColumnMap;
			}
			set
			{
				if ((this._ColumnMap != value))
				{
					this._ColumnMap = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
