#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3620
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OwensCorning.RoofingServices.Database.data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="OCroofingDEV")]
	public partial class RoofingLeadsInformationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public RoofingLeadsInformationDataContext() : 
				base(global::OwensCorning.RoofingServices.Properties.Settings.Default.OCroofingDEVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RoofingLeadsInformationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoofingLeadsInformationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoofingLeadsInformationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RoofingLeadsInformationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RfgRequestQuote> RfgRequestQuotes
		{
			get
			{
				return this.GetTable<RfgRequestQuote>();
			}
		}
		
		[Function(Name="dbo.GetRoofingLeads")]
		public ISingleResult<GetRoofingLeadsResult> GetRoofingLeads([Parameter(DbType="VarChar(255)")] string memberID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), memberID);
			return ((ISingleResult<GetRoofingLeadsResult>)(result.ReturnValue));
		}
	}
	
	[Table(Name="dbo.RfgRequestQuote")]
	public partial class RfgRequestQuote
	{
		
		private int _id;
		
		private string _name;
		
		private string _address;
		
		private string _city;
		
		private string _state;
		
		private string _zip;
		
		private string _email;
		
		private string _phone;
		
		private string _description;
		
		private string _forwardedTo;
		
		private string _forwardedToIds;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _besttimetocall;
		
		public RfgRequestQuote()
		{
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[Column(Storage="_address", DbType="VarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[Column(Storage="_city", DbType="VarChar(100)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[Column(Storage="_state", DbType="VarChar(50)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[Column(Storage="_zip", DbType="VarChar(50)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this._zip = value;
				}
			}
		}
		
		[Column(Storage="_email", DbType="VarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[Column(Storage="_phone", DbType="VarChar(25)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[Column(Storage="_description", DbType="VarChar(1024)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[Column(Storage="_forwardedTo", DbType="VarChar(MAX)")]
		public string forwardedTo
		{
			get
			{
				return this._forwardedTo;
			}
			set
			{
				if ((this._forwardedTo != value))
				{
					this._forwardedTo = value;
				}
			}
		}
		
		[Column(Storage="_forwardedToIds", DbType="VarChar(1024)")]
		public string forwardedToIds
		{
			get
			{
				return this._forwardedToIds;
			}
			set
			{
				if ((this._forwardedToIds != value))
				{
					this._forwardedToIds = value;
				}
			}
		}
		
		[Column(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[Column(Storage="_besttimetocall", DbType="VarChar(50)")]
		public string besttimetocall
		{
			get
			{
				return this._besttimetocall;
			}
			set
			{
				if ((this._besttimetocall != value))
				{
					this._besttimetocall = value;
				}
			}
		}
	}
	
	public partial class GetRoofingLeadsResult
	{
		
		private int _id;
		
		private string _name;
		
		private string _address;
		
		private string _city;
		
		private string _state;
		
		private string _zip;
		
		private string _email;
		
		private string _phone;
		
		private string _description;
		
		private string _forwardedTo;
		
		private string _forwardedToIds;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _besttimetocall;
		
		public GetRoofingLeadsResult()
		{
		}
		
		[Column(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[Column(Storage="_address", DbType="VarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[Column(Storage="_city", DbType="VarChar(100)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[Column(Storage="_state", DbType="VarChar(50)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[Column(Storage="_zip", DbType="VarChar(50)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this._zip = value;
				}
			}
		}
		
		[Column(Storage="_email", DbType="VarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[Column(Storage="_phone", DbType="VarChar(25)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[Column(Storage="_description", DbType="VarChar(1024)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[Column(Storage="_forwardedTo", DbType="VarChar(MAX)")]
		public string forwardedTo
		{
			get
			{
				return this._forwardedTo;
			}
			set
			{
				if ((this._forwardedTo != value))
				{
					this._forwardedTo = value;
				}
			}
		}
		
		[Column(Storage="_forwardedToIds", DbType="VarChar(1024)")]
		public string forwardedToIds
		{
			get
			{
				return this._forwardedToIds;
			}
			set
			{
				if ((this._forwardedToIds != value))
				{
					this._forwardedToIds = value;
				}
			}
		}
		
		[Column(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[Column(Storage="_besttimetocall", DbType="VarChar(50)")]
		public string besttimetocall
		{
			get
			{
				return this._besttimetocall;
			}
			set
			{
				if ((this._besttimetocall != value))
				{
					this._besttimetocall = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
